logging:
  level: INFO
  loggers:
    com.duberton: DEBUG

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

github:
  url: 'https://api.github.com'